version: '3'
services:
  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master Port
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-network

  spark-worker-1:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-network

  spark-worker-2:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"  # Jupyter Notebook
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - .:/home/jovyan/work
    networks:
      - spark-network

networks:
  spark-network:
    external: true
